apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting for database; sleep 2; done;']
      containers:
      - name: php
        image: rafasaez/php-sql-app:latest
        ports:
        - containerPort: 80